spring:
  h2:
    console:
      enabled: true      # H2 콘솔 사용 여부
      path: /h2-console  # 접속 주소 설정
  datasource:
    # 메모리 모드 사용 시 (서버 재시작 시 데이터 초기화)
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: